# This is a basic workflow to help you get started with Actions

name: deploy

on:
  push:
    branches:
      - main
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable' # or: 'beta' or 'master'
      - run: |
          flutter pub get
          flutter build web
      - uses: canastro/copy-file-action@master
        with:
          source: "build/web"
          target: "build/"
